### PR TITLE
Add AKS Istio and Open service mesh support

### PR DESCRIPTION
**Pull request by trapeznikov**
## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

Open Service Mesh:
```
Terraform will perform the following actions:

  # module.solution.module.aks_clusters["aks_re1"].azurerm_kubernetes_cluster.aks will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks" {
        id                                  = "/subscriptions/xxx/resourceGroups/poes-rg-aks-workloads-cac/providers/Microsoft.ContainerService/managedClusters/poes-aks-workloads-cac"
        name                                = "poes-aks-workloads-cac"
      ~ open_service_mesh_enabled           = false -> true
        tags                                = {
            "Env"             = "es"
            "caf_environment" = "es"
            "caf_level"       = "level3"
            "module"          = "aks"
            "rover_version"   = "aztfmod/rover:1.3.10-2311.0601"
        }
        # (28 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }
```
Istio (This requires that the Preview Feature Microsoft.ContainerService/AzureServiceMeshPreview is enabled and the Resource Provider is re-registered, see [the documentation](https://learn.microsoft.com/en-us/azure/aks/istio-deploy-addon#register-the-azureservicemeshpreview-feature-flag) for more information.)
```
  # module.solution.module.aks_clusters["aks_re1"].azurerm_kubernetes_cluster.aks will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks" {
        id                                  = "/subscriptions/xxx/resourceGroups/poes-rg-aks-workloads-cac/providers/Microsoft.ContainerService/managedClusters/poes-aks-workloads-cac"
        name                                = "poes-aks-workloads-cac"
        tags                                = {
            "Env"             = "es"
            "caf_environment" = "es"
            "caf_level"       = "level3"
            "module"          = "aks"
            "rover_version"   = "aztfmod/rover:1.3.10-2311.0601"
        }
        # (29 unchanged attributes hidden)

      + service_mesh_profile {
          + internal_ingress_gateway_enabled = true
          + mode                             = "Istio"
        }

        # (8 unchanged blocks hidden)
    }
```

### CODE REVIEW

**Comment by trapeznikov** [comment]
Actually OSM project was archived, so maybe this PR is not needed. Feel free to reject it.

**Review by arnaudlh — CHANGES_REQUESTED** [review]
Thanks for your PR @trapeznikov, do you mind adding an example with the preview flags as described here: https://github.com/aztfmod/terraform-azurerm-caf/blob/azurerm-update-2401/examples/compute/kubernetes_services/104-private-cluster/aks.tfvars#L2 and add it to the JSON workflows for CI/CD to pick it up? Thanks!

**Comment by trapeznikov** [comment]
@arnaudlh I added only Istio example, because Open Service Mesh project was archived by CNCF in favour of Istio. Do you want me to remove OSM config entirely, or keep both, but only one example?

**Comment by arnaudlh** [comment]
thanks for your PR @trapeznikov

**Pull request merged**
