### PR TITLE
Virtual machine scale set keyvault extension

### PR DESCRIPTION
**Pull request by hyperfocus1337**
This PR adds the azurerm_virtual_machine_scale_set_extension keyvault resource. It supports dynamically specifying identity_type and managed_identity_key values. Related to https://github.com/Azure/caf-terraform-landingzones/pull/313.

Dynamic key vault selection code is pending.

### CODE REVIEW

**Comment by hyperfocus1337** [comment]
The plan output is now properly being shown while testing with: `terraform plan --var-file examples/compute/virtual_machine_scale_set/106-linux-win-vmss-keyvault-extension/configuration.tfvars`.

The `settings` names have been kept similar to the documentation: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/key-vault-windows

Dynamic keyvault selection pending.

**Comment by arnaudlh** [comment]
hi @hyperfocus1337 and thanks for your PR! 
Testing the branch and just doing a plan, I get the following error:

```
@calling terraform_plan -- azurerm
╷
│ Error: Unsupported attribute
│ 
│   on ../modules/compute/virtual_machine_scale_set_extensions/key_vault.tf line 24, in resource "azurerm_virtual_machine_scale_set_extension" "keyvault":
│   24:       "observedCertificates" : try(var.extension.secretsManagementSettings.observedCertificates, data.azurerm_key_vault_certificate.observedCertificates["enabled"].value)
│ 
│ This object has no argument, nested block, or exported attribute named "value".
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../modules/compute/virtual_machine_scale_set_extensions/key_vault.tf line 24, in resource "azurerm_virtual_machine_scale_set_extension" "keyvault":
│   24:       "observedCertificates" : try(var.extension.secretsManagementSettings.observedCertificates, data.azurerm_key_vault_certificate.observedCertificates["enabled"].value)
│ 
│ This object has no argument, nested block, or exported attribute named "value".
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../modules/compute/virtual_machine_scale_set_extensions/key_vault.tf line 24, in resource "azurerm_virtual_machine_scale_set_extension" "keyvault":
│   24:       "observedCertificates" : try(var.extension.secretsManagementSettings.observedCertificates, data.azurerm_key_vault_certificate.observedCertificates["enabled"].value)
│ 
│ This object has no argument, nested block, or exported attribute named "value".
╵
Terraform plan return code: 1
Error on or near line 391: Error running terraform plan; exiting with status 1
```

Anything I missed? 
thanks/cheers
Arnaud

**Comment by hyperfocus1337** [comment]
That's due to the dynamic keyvault commits, that work is not done yet. Thanks for the review.

**Comment by hyperfocus1337** [comment]
Moved extension to the new location as per https://github.com/aztfmod/terraform-azurerm-caf/pull/957#issuecomment-1058849835

**Review by arnaudlh — APPROVED** [review]
LGTM

**Pull request merged**
