### PR TITLE
Add vm replicated

### PR DESCRIPTION
**Pull request by naeemdhby**
# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

### CODE REVIEW

**Comment by arnaudlh** [comment]
@naeemdhby - ready for review? :)

**Comment by naeemdhby** [comment]
@arnaudlh I may need help on this, it is getting an unknown error from azure when trying to deploy, I don't think the issue is from module, could be from how I set up the example, would you please review my example and see if looks ok on how I defined other resources and resources, maybe type of other resources are not compatible with VM replicated module.

**Comment by arnaudlh** [comment]
sure @naeemdhby, let me have a look and test early next week

**Comment by LaurentLesle** [comment]
closing as being draft for 1 year

**Pull request closed without merging**
