### PR TITLE
Added changes related to application gateway redirect (v1)

### PR DESCRIPTION
**Pull request by didayal-msft**
# [1719](https://github.com/aztfmod/terraform-azurerm-caf/issues/1719)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Added feature to create redirect configuration and link it to routing rules. Both external site redirection and listener redirection examples have been added.

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

### CODE REVIEW

**Review by LaurentLesle — APPROVED** [review]
LGTM - Will approve and run the CI

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
thanks for the PR @didayal-msft, I'm getting an error when deploying example 303:
Are you able to repro and feedback? thanks

```
module.example.module.application_gateway_applications["demo_app1"].null_resource.set_request_routing_rule["external1"] (local-exec): ERROR: (InvalidResourceReference) Resource /subscriptions/a-b-c-d-e/resourceGroups/lbzt-rg-example-agw/providers/Microsoft.Network/applicationGateways/lbzt-agw-app_gateway_example/redirectConfigurations/redirect-https referenced by resource /subscriptions/a-b-c-d-e/resourceGroups/lbzt-rg-example-agw/providers/Microsoft.Network/applicationGateways/lbzt-agw-app_gateway_example/requestRoutingRules/demo_app1_external_rd_listener was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
module.example.module.application_gateway_applications["demo_app1"].null_resource.set_request_routing_rule["external1"] (local-exec): Code: InvalidResourceReference
module.example.module.application_gateway_applications["demo_app1"].null_resource.set_request_routing_rule["external1"] (local-exec): Message: Resource /subscriptions/a-b-c-d-e/resourceGroups/lbzt-rg-example-agw/providers/Microsoft.Network/applicationGateways/lbzt-agw-app_gateway_example/redirectConfigurations/redirect-https referenced by resource /subscriptions/a-b-c-d-e/resourceGroups/lbzt-rg-example-agw/providers/Microsoft.Network/applicationGateways/lbzt-agw-app_gateway_example/requestRoutingRules/demo_app1_external_rd_listener was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
```

**Comment by didayal-msft** [comment]
I deployed again and it deployed without errors. 
I also checked the dependencies:
redirect config depends on listener: null_resource.set_http_listener
routing rule depends on redirect config (null_resource.set_redirect_configurations)

image

**Comment by arnaudlh** [comment]
@didayal-msft - got it working but got a comparable error on destroy, will wait for your testing on it.

**Comment by arnaudlh** [comment]
> @didayal-msft - got it working but got a comparable error on destroy, will wait for your testing on it.

any update on the destroy process @didayal-msft?

**Pull request merged**
