### PR TITLE
Adding azure automation runbook and schedule

### PR DESCRIPTION
**Pull request by sharmilamusunuru**
# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [x] NO

### CODE REVIEW

**Comment by schoenr79** [comment]
@sharmilamusunuru  think we opened a PR nearly simultaneously for the same feature are automation runbooks.
https://github.com/aztfmod/terraform-azurerm-caf/pull/1361 / Issue: https://github.com/aztfmod/terraform-azurerm-caf/issues/1273

Mine is without runbook schedule, but i added reading the content from a script file, too.

**Comment by arnaudlh** [comment]
@schoenr79 @sharmilamusunuru - Thank you so much for your contributions, I will try to make the best of both worlds at merge time :)

**Review by arnaudlh — APPROVED** [review]
Will fix at merge time.

**Comment by schoenr79** [comment]
thank u for the update @arnaudlh the following days i will still work on integrating azurerm_automation_job_schecule, and try to refactor the current merge a bit.

**Pull request merged**
