### PR TITLE
fixed resolving of backend address pool name for application gateway path rule

### PR DESCRIPTION
**Pull request by swilkodev**
This PR addresses issue #586. I took the minimalistic approach for now.

### CODE REVIEW

**Review by iriahk89 — COMMENTED** [review]
your configuration need to be updated. I put the comment in your issue. let me know if any further clarification needed

**Review by iriahk89 — COMMENTED** [review]
LGTM

**Review by iriahk89 — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
thanks for your PR @swilkodev - moving to integration branch!

**Pull request merged**
