### PR TITLE
MS SQL Vulnerability assessment storage

### PR DESCRIPTION
**Pull request by jleonelion**
Fixing https://github.com/aztfmod/terraform-azurerm-caf/issues/280

### CODE REVIEW

**Review by arnaudlh — CHANGES_REQUESTED** [review]
hi @jleonelion can you please rebase (merge) on branch 5.3.0_preview as your previously integrated changes are staged there. 
thanks.

**Comment by jleonelion** [comment]
@arnaudlh sorry about that.  branch merged so this PR is just the changes to address the issue at hand

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
thanks for your contribution @jleonelion

**Pull request merged**
