### PR TITLE
Update rover jan 2023

### PR DESCRIPTION
**Pull request by arnaudlh**
Update to rover.

### CODE REVIEW

**Comment by iriahk89** [comment]
LGTM!

**Review by iriahk89 — COMMENTED** [review]
LGTM!

**Review by iriahk89 — APPROVED** [review]
LGTM!

**Comment by MarcelHeek** [comment]
Not to mingle too much, but should there not be a (official) release (document) for this version first in the aztfmod/rover repo/[releases](https://github.com/aztfmod/rover/releases)?

**Pull request merged**
