### PR TITLE
Add IoT capabilities 

### PR DESCRIPTION
**Pull request by sschne**
# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [x] NO

### CODE REVIEW

**Comment by arnaudlh** [comment]
hi @sschne, I have updated under: https://github.com/aztfmod/terraform-azurerm-caf/tree/sschne-f/iot-upstream-new so we can iterate. 

We should be closer to it by: 
1. Making sure all naming provider options are implemented.
2. Making sure all cross LZ capabilities are implemented.

**Comment by sschne** [comment]
Hey @arnaudlh ,
i have updated the PR accordingly. All naming provider resources are added in https://github.com/aztfmod/terraform-provider-azurecaf/pull/236. Cross-LZ compatibilities should be set. Also made some other changes:
- added resource references for eventhub/storage account/identities 
- resourcegroup / location locals in the module as per latest updates
- updated tests

One test is not working ( 102-iot-hub-endpoints-identity-based ), as the identity needs the role assignment to eventhub/sa before adding the endpoint to iothub. We could solve this in using azurerm_iothub_endpoint_* resources and let them depend explicitly on azurerm_role_assignment.for, what do you think?

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
thanks for the contribution @sschne!

**Pull request merged**
