### PR TITLE
Updating URL rewrite rule for Application Gateway

### PR DESCRIPTION
**Pull request by gaofei88**
with [1], the content will never get any value

### CODE REVIEW

**Comment by LaurentLesle** [comment]
Hi @gaofei88 You have spotted a bug indeed however the resolution you are proposing is not valid.

url is one optional block in the 'rewrite_rule' block as per the documentation
image

if you do the following code you can potentially end-up with multiple url block. We have documented the pattern in the wiki - https://github.com/aztfmod/terraform-azurerm-caf/wiki/Single-Optional-Block
```hcl
   for_each = try([rewrite_rule.value.url], [])
```

so I think the code should be:
```hcl
          dynamic "url" {
            for_each = try(rewrite_rule.value.url, null) == null ? [] : [1]
            content {
              path         = try(rewrite_rule.value.url.path, null)
              query_string = try(rewrite_rule.value.url.query_string, null)
              reroute      = try(rewrite_rule.value.url.reroute, null)
            }
          }

```

Let me know if you agree with that and I let you updating the PR.

**Comment by LaurentLesle** [comment]
@iriahk89 @jorseng for your visibility

**Comment by gaofei88** [comment]
@LaurentLesle  Agree with your codes. Have updated the PR with that. Cheers.

**Review by arnaudlh — APPROVED** [review]
LGTM

**Pull request merged**
