### PR TITLE
Upgrade to azurerm 3.9.0

### PR DESCRIPTION
**Pull request by arnaudlh**
This PR is to cover upgrade to azurerm 3.9.0

### CODE REVIEW

**Comment by nusrath432** [comment]
@arnaudlh @SergioMiyama  How does this upgrade align with Rover & caf-terraform-landingzones (https://github.com/Azure/caf-terraform-landingzones) - if we could have a Roadmap / upgrade pinned up ticket / wiki it would be very helpful, please.

**Comment by bkarstaedt** [comment]
@arnaudlh how great is the chance to upgrade `azurerm` to latest (3.28.0)?

For `azurerm_storage_account` the `immutability_policy` is introduced which would be great for WORM archiving scenarios...

**Comment by eoware** [comment]
> @arnaudlh @SergioMiyama How does this upgrade align with Rover & caf-terraform-landingzones (https://github.com/Azure/caf-terraform-landingzones) - if we could have a Roadmap / upgrade pinned up ticket / wiki it would be very helpful, please.

This would be nice to know. The current CAF starter uses Standard SKU firewalls which can't be changed to the new Basic SKU because the AzureRM version doesn't recognize the SKU.

**Comment by brk3** [comment]
@arnaudlh @LaurentLesle Anything the community can do to help this PR along?

**Comment by MrTolerant** [comment]
Good day! How we can help with updating to latest azurerm?
Can spend couple of days;

**Comment by hadiulla** [comment]
When can we expect this PR to be merged? This is becoming blocker for most of the community because of this bug - https://github.com/aztfmod/terraform-azurerm-caf/issues/1173

**Comment by arnaudlh** [comment]
@MrTolerant @hadiulla @brk3 @eoware @bkarstaedt @nusrath432 thanks folks for the energy! 

We are all looking forward for this update to pass! @LaurentLesle and myself are working on it in the next few days. 

For the really impatient, you can follow the branch ```int-azrm-3.44.1``` where we are polishing things up.

Roadmap: 

Get ```5.7.0``` (this module update to azurerm 3.x) to work with all examples and with minor config file edits, and we will be assessing reasonable backport to ```5.6.x``` of bugs we found  in 

Once it is out, you we can start integrating feature upgrades and augmentation. 

Hope that clarifies! I will close this PR and we will open a new one on new branch in the next few days!

**Comment by nusrath432** [comment]
@arnaudlh @LaurentLesle Thank you for all the hard work ... appreciate your efforts.

**Pull request closed without merging**
