### PR TITLE
Add support for storage_mode_type in recovery vaults

### PR DESCRIPTION
**Pull request by chengwang514**
RSV storage_mode_type with all 3 options (ZRS, GRS and LRS) started to be supported in azurerm version 2.95.

### CODE REVIEW

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
hi @chengwang514 thanks for your contribution to CAF Terraform for Azure!

**Comment by chengwang514** [comment]
Thanks @arnaudlh , updated azurerm version to 2.98 as requested by Laurent.

**Comment by cheng514** [comment]
@cheng514 mark PR

**Pull request merged**
