### PR TITLE
Backup vault for storage account

### PR DESCRIPTION
**Pull request by yuri-shpik**
Add complete support of the backup vault for the storage account. Also, added in roles.tf possibility to add needed role for backup instance configuration.

### CODE REVIEW

**Review by arnaudlh — CHANGES_REQUESTED** [review]
Thanks for the PR guys, it looks great, however there are a lot of extra changes and commits. Do you think you can submit another PR with just the changes releveant to backup vault? 

thanks
Arnaud

**Comment by sschne** [comment]
Hi,
we would also need support for data protection backup vault for data disks. Should we wait for this to be merged, or should i build upon this PR?

**Comment by arnaudlh** [comment]
> Hi, we would also need support for data protection backup vault for data disks and postgresql. Should we wait for this to be merged, or should i build upon this PR?

hi @sschne, I'll see what I can do this week to remove the noise out and forward it to 5.6.0 if possible.

**Comment by arnaudlh** [comment]
hi @yuri-shpik! Thank you, you have done an amazing job with this PR, I will merge #1110 as it filters out a lot of extra commit that were also in your branch.

**Comment by arnaudlh** [comment]
hi @yuri-shpik! Thank you, you have done an amazing job with this PR, I will merge #1110 as it filters out a lot of extra commit that were also in your branch.

**Comment by arnaudlh** [comment]
Closing as using https://github.com/aztfmod/terraform-azurerm-caf/pull/1110

**Pull request closed without merging**
