### PR TITLE
Added support for image_registry_credentials to container groups

### PR DESCRIPTION
**Pull request by JvHd-vw**
Updated container groups to now support image_registry_credentials.
 A example is provided using dynamic_keyvault_secrets as as credential source.

### CODE REVIEW

**Comment by LaurentLesle** [comment]
Thanks @JvHd-vw . Let me test it as we may be able to include it into today's release

**Review by LaurentLesle — APPROVED** [review]
Thanks @JvHd-vw for the PR

**Review by arnaudlh — CHANGES_REQUESTED** [review]
Getting the following error on running the examples
:
image

**Comment by JvHd-vw** [comment]
> Getting the following error on running the examples : image
I will have a look

**Comment by JvHd-vw** [comment]
The dynamic_keyvault_secrets are created but somehow the datasource is reading them before they are available. Will investigate

**Comment by JvHd-vw** [comment]
@arnaudlh Should be fixed now. I forgot a depends_on.

**Review by arnaudlh — APPROVED** [review]
LGTM

**Comment by arnaudlh** [comment]
thanks for the PR @JvHd-vw

**Pull request merged**
