### PR TITLE
add dynamic value to dynamic kv secret

### PR DESCRIPTION
**Pull request by anasmohana**
this new feature allows the users to create a new random dynamic password as a secret directly by adding the value of the secret equal to "dynamic" and adding a new config object to send the configurations of the new password.

### CODE REVIEW

**Comment by arnaudlh** [comment]
Sure @anasmohana, basically when you add an example set of tfvars files inside the /examples folder. You can add them to the list of examples tested in CD/CD by adding the reference to the path inside the following file: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/.github/workflows/standalone-scenarios.json

**Comment by arnaudlh** [comment]
Sure @anasmohana, basically when you add an example set of tfvars files inside the /examples folder. You can add them to the list of examples tested in CD/CD by adding the reference to the path inside the following file: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/.github/workflows/standalone-scenarios.json

**Comment by anasmohana** [comment]
I have added an example :)

**Comment by LaurentLesle** [comment]
Very good addition - thanks for the PR.
Tests are good
image

**Review by LaurentLesle — APPROVED** [review]
LGTM

**Pull request merged**
