### PR TITLE
Allow legacy method for VM creation with data disk at boot time

### PR DESCRIPTION
**Pull request by abdulrabbani00**
This PR will capture the old vm creation module.

### CODE REVIEW

**Comment by LaurentLesle** [comment]
Thanks @abdulrabbani00 Let me test it first. Looks like a pragmatic way to unblock marketplace images with additional data disks

**Comment by abdulrabbani00** [comment]
> Thanks @abdulrabbani00 Let me test it first. Looks like a pragmatic way to unblock marketplace images with additional data disks

Hello @LaurentLesle,

I have tested both the windows and Linux machine creation with custom images and data disks attached. I had difficulties testing the data disk attachment with marketplace images since most of them do not accept additional data disks on bootup.

Please let me know the outcome of your test.

**Comment by abdulrabbani00** [comment]
@arnaudlh  - I have cleared the PR and removed the previous commits. @LaurentLesle - Please provide your feedback once you have tested this on your side, and feel free to make any changes for the merge.

**Review by arnaudlh — APPROVED** [review]
looks good to me to resolve the specific problem

**Pull request merged**
