### PR TITLE
Added default ssl_policy block to AGW

### PR DESCRIPTION
**Pull request by shanoor**
## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Does this introduce a breaking change

- [ ] YES
- [x] NO

### CODE REVIEW

**Comment by arnaudlh** [comment]
hi @shanoor, we tend to decorelate and use both application_gateway_platform and application_gateway_application.
Have you tried using it and they dont fit your need?

**Comment by LaurentLesle** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/22669

**Review by arnaudlh — APPROVED** [review]
LGTM, will add example and CI in separate PR @LaurentLesle

**Comment by arnaudlh** [comment]
thanks for your PR @shanoor

**Pull request merged**
